# Generated by Django 5.0.6 on 2024-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='suggestion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
