# Generated by Django 5.0.6 on 2024-05-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='suggestion',
        ),
    ]
